FROM python_bonobo

# running migrations
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py collectstatic --no-input

# gunicorn
CMD ["gunicorn", "--config", "gunicorn-cfg.py", "core.wsgi"]
