#!/bin/bash

FAILURE=1
SUCCESS=0

function exit_on_error {
	if [ $? -ne 0 ]; then
		echo "An error appeared, aborting Image Creation"
		exit $FAILURE
	fi
}

function build_all {
        docker build -t python_bonobo:latest -f Dockerfile.base --no-cache .
	exit_on_error
        docker build -t bonobo_board:latest -f Dockerfile.django --no-cache .
	exit_on_error
}

function build_django {
        docker build -t bonobo_board:latest -f Dockerfile.django --no-cache .
	exit_on_error
}

while getopts ad flag
do
	case "${flag}" in
		a) build_all;;
		d) build_django;;
	esac
done

exit $SUCCESS
